import { useState, useCallback, useMemo } from "react";

/**
 * AI Personality System — SOUL.md-inspired (OpenClaw pattern).
 *
 * A living document that defines who Blade is TO YOU.
 * Accumulates over time. Never resets. Gets richer daily.
 *
 * Sections:
 * - Identity: who the user is
 * - Preferences: how they want responses
 * - Projects: what they're working on
 * - Skills: what they know
 * - Contacts: people they mention
 * - Goals: what they're trying to achieve
 * - History: key decisions and milestones
 */

export interface SoulSection {
  id: string;
  title: string;
  icon: string;
  content: string;
  autoGenerated: boolean;
  lastUpdated: number;
  entryCount: number;
}

export interface SoulDocument {
  version: number;
  createdAt: number;
  updatedAt: number;
  sections: SoulSection[];
  rawMarkdown: string;
}

const STORAGE_KEY = "blade-soul";

const DEFAULT_SECTIONS: Omit<SoulSection, "lastUpdated" | "entryCount">[] = [
  { id: "identity", title: "Identity", icon: "👤", content: "", autoGenerated: false },
  { id: "preferences", title: "Preferences", icon: "⚙️", content: "", autoGenerated: false },
  { id: "projects", title: "Projects", icon: "📁", content: "", autoGenerated: false },
  { id: "skills", title: "Skills & Expertise", icon: "🎯", content: "", autoGenerated: false },
  { id: "contacts", title: "People", icon: "🤝", content: "", autoGenerated: false },
  { id: "goals", title: "Goals", icon: "🎯", content: "", autoGenerated: false },
  { id: "history", title: "Key Decisions", icon: "📋", content: "", autoGenerated: false },
  { id: "tools", title: "Tech Stack", icon: "🔧", content: "", autoGenerated: false },
  { id: "style", title: "Communication Style", icon: "💬", content: "", autoGenerated: false },
  { id: "notes", title: "Misc Notes", icon: "📝", content: "", autoGenerated: false },
];

function createDefaultSoul(): SoulDocument {
  const now = Date.now();
  return {
    version: 1,
    createdAt: now,
    updatedAt: now,
    sections: DEFAULT_SECTIONS.map((s) => ({
      ...s,
      lastUpdated: now,
      entryCount: 0,
    })),
    rawMarkdown: "",
  };
}

function loadSoul(): SoulDocument {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : createDefaultSoul();
  } catch {
    return createDefaultSoul();
  }
}

function saveSoul(soul: SoulDocument) {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(soul));
}

function generateMarkdown(sections: SoulSection[]): string {
  const lines = ["# SOUL.md — Who I Am to Blade\n"];
  for (const section of sections) {
    if (!section.content.trim()) continue;
    lines.push(`## ${section.icon} ${section.title}\n`);
    lines.push(section.content.trim());
    lines.push("");
  }
  return lines.join("\n");
}

// Auto-extract information from user messages
function extractSoulData(messages: Array<{ role: string; content: string }>): Record<string, string[]> {
  const extracted: Record<string, string[]> = {};

  for (const msg of messages) {
    if (msg.role !== "user") continue;
    const content = msg.content;

    // Identity patterns
    const nameMatch = content.match(/(?:my name is|I'm|I am)\s+([A-Z][a-z]+(?:\s+[A-Z][a-z]+)?)/);
    if (nameMatch) {
      extracted["identity"] = extracted["identity"] || [];
      extracted["identity"].push(`Name: ${nameMatch[1]}`);
    }

    const roleMatch = content.match(/(?:I'm a|I am a|I work as|my role is|my job is)\s+([^.!?]+)/i);
    if (roleMatch) {
      extracted["identity"] = extracted["identity"] || [];
      extracted["identity"].push(`Role: ${roleMatch[1].trim()}`);
    }

    // Preferences
    const prefMatch = content.match(/(?:I prefer|I like|I want|I always|I never)\s+([^.!?]+)/gi);
    if (prefMatch) {
      extracted["preferences"] = extracted["preferences"] || [];
      extracted["preferences"].push(...prefMatch.map((p) => p.trim()));
    }

    // Projects
    const projMatch = content.match(/(?:I'm (?:working on|building)|my project|my app)\s+([^.!?]+)/gi);
    if (projMatch) {
      extracted["projects"] = extracted["projects"] || [];
      extracted["projects"].push(...projMatch.map((p) => p.trim()));
    }

    // Skills
    const skillMatch = content.match(/(?:I know|I'm experienced in|I've been (?:using|writing)|I'm familiar with)\s+([^.!?]+)/gi);
    if (skillMatch) {
      extracted["skills"] = extracted["skills"] || [];
      extracted["skills"].push(...skillMatch.map((s) => s.trim()));
    }

    // Tech stack
    const techPatterns = [
      "typescript", "javascript", "python", "rust", "go", "java",
      "react", "vue", "angular", "svelte", "next.js",
      "tauri", "electron", "node", "deno", "bun",
      "docker", "kubernetes", "aws", "gcp", "azure",
      "postgres", "mysql", "sqlite", "mongodb", "redis",
    ];
    const found = techPatterns.filter((t) => content.toLowerCase().includes(t));
    if (found.length > 0) {
      extracted["tools"] = extracted["tools"] || [];
      extracted["tools"].push(...found.map((t) => t.charAt(0).toUpperCase() + t.slice(1)));
    }

    // Goals
    const goalMatch = content.match(/(?:I want to|I'm trying to|my goal is|I need to)\s+([^.!?]+)/gi);
    if (goalMatch) {
      extracted["goals"] = extracted["goals"] || [];
      extracted["goals"].push(...goalMatch.map((g) => g.trim()));
    }
  }

  // Deduplicate each section
  for (const key of Object.keys(extracted)) {
    extracted[key] = [...new Set(extracted[key])];
  }

  return extracted;
}

export function useAIPersonality() {
  const [soul, setSoul] = useState<SoulDocument>(loadSoul);

  const updateSection = useCallback((sectionId: string, content: string) => {
    setSoul((prev) => {
      const next = {
        ...prev,
        updatedAt: Date.now(),
        sections: prev.sections.map((s) =>
          s.id === sectionId
            ? { ...s, content, lastUpdated: Date.now(), entryCount: content.split("\n").filter(Boolean).length }
            : s,
        ),
      };
      next.rawMarkdown = generateMarkdown(next.sections);
      saveSoul(next);
      return next;
    });
  }, []);

  const appendToSection = useCallback((sectionId: string, line: string) => {
    setSoul((prev) => {
      const section = prev.sections.find((s) => s.id === sectionId);
      if (!section) return prev;

      // Don't add duplicates
      if (section.content.includes(line.trim())) return prev;

      const newContent = section.content
        ? `${section.content}\n- ${line.trim()}`
        : `- ${line.trim()}`;

      const next = {
        ...prev,
        updatedAt: Date.now(),
        sections: prev.sections.map((s) =>
          s.id === sectionId
            ? { ...s, content: newContent, lastUpdated: Date.now(), entryCount: newContent.split("\n").filter(Boolean).length }
            : s,
        ),
      };
      next.rawMarkdown = generateMarkdown(next.sections);
      saveSoul(next);
      return next;
    });
  }, []);

  const ingestFromConversation = useCallback((messages: Array<{ role: string; content: string }>) => {
    const extracted = extractSoulData(messages);
    for (const [sectionId, items] of Object.entries(extracted)) {
      for (const item of items.slice(0, 3)) {
        appendToSection(sectionId, item);
      }
    }
  }, [appendToSection]);

  // Generate system prompt context from SOUL
  const getSystemPromptContext = useCallback((): string => {
    const filledSections = soul.sections.filter((s) => s.content.trim());
    if (filledSections.length === 0) return "";

    const lines = ["[About this user — from SOUL.md]"];
    for (const section of filledSections) {
      lines.push(`${section.icon} ${section.title}:`);
      // Only include first 5 lines per section to save tokens
      const sectionLines = section.content.split("\n").filter(Boolean).slice(0, 5);
      lines.push(...sectionLines);
    }
    return lines.join("\n");
  }, [soul]);

  const exportAsMarkdown = useCallback((): string => {
    return generateMarkdown(soul.sections);
  }, [soul]);

  const importFromMarkdown = useCallback((markdown: string) => {
    // Parse markdown sections back into soul
    const sections = [...soul.sections];
    const sectionRegex = /^## .+ (.+)$/gm;
    let match;
    let lastSectionId: string | null = null;
    let lastIndex = 0;

    while ((match = sectionRegex.exec(markdown)) !== null) {
      if (lastSectionId && lastIndex > 0) {
        const content = markdown.slice(lastIndex, match.index).trim();
        const section = sections.find((s) => s.id === lastSectionId);
        if (section) section.content = content;
      }
      const title = match[1];
      const foundSection = sections.find((s) => s.title === title);
      lastSectionId = foundSection?.id || null;
      lastIndex = match.index + match[0].length;
    }

    // Last section
    if (lastSectionId && lastIndex > 0) {
      const content = markdown.slice(lastIndex).trim();
      const section = sections.find((s) => s.id === lastSectionId);
      if (section) section.content = content;
    }

    setSoul((prev) => {
      const next = { ...prev, sections, updatedAt: Date.now(), rawMarkdown: markdown };
      saveSoul(next);
      return next;
    });
  }, [soul]);

  const stats = useMemo(() => ({
    totalEntries: soul.sections.reduce((s, sec) => s + sec.entryCount, 0),
    filledSections: soul.sections.filter((s) => s.content.trim()).length,
    totalSections: soul.sections.length,
    lastUpdated: soul.updatedAt,
    age: Date.now() - soul.createdAt,
  }), [soul]);

  const clear = useCallback(() => {
    const fresh = createDefaultSoul();
    setSoul(fresh);
    saveSoul(fresh);
  }, []);

  return {
    soul,
    sections: soul.sections,
    updateSection,
    appendToSection,
    ingestFromConversation,
    getSystemPromptContext,
    exportAsMarkdown,
    importFromMarkdown,
    stats,
    clear,
  };
}
