// src/lib/tauri/intelligence.ts — Phase 14 Plan 14-02 (WIRE2-04)
//
// Wrappers for godmode.rs, proactive_engine.rs, proactive_vision.rs,
// causal_graph.rs, consequence.rs, brain.rs, dream_mode.rs.
// D-36 file-per-cluster discipline: intelligence backend → own TS file.
// All commands are already registered in lib.rs — no Rust changes required.
//
// @see src-tauri/src/godmode.rs
// @see src-tauri/src/proactive_engine.rs
// @see src-tauri/src/causal_graph.rs
// @see src-tauri/src/consequence.rs
// @see src-tauri/src/brain.rs
// @see src-tauri/src/dream_mode.rs
// @see .planning/phases/14-wiring-accessibility-pass/14-02-PLAN.md

import { invokeTyped } from './_base';

/** Proactive task as returned by proactive_engine.rs. */
export type ProactiveTask = {
  id: string;
  summary: string;
  priority: number;
  source: string;
};

/**
 * Return active proactive tasks generated by the proactive engine.
 * Read-only.
 * @see proactive_engine.rs `pub fn get_proactive_tasks() -> Vec<ProactiveTask>`
 */
export function getProactiveTasks(): Promise<ProactiveTask[]> {
  return invokeTyped<ProactiveTask[]>('get_proactive_tasks');
}

/**
 * Return pending (unactioned) proactive task cards.
 * Read-only.
 * @see proactive_engine.rs `pub fn proactive_get_pending() -> Vec<ProactiveTask>`
 */
export function proactiveGetPending(): Promise<ProactiveTask[]> {
  return invokeTyped<ProactiveTask[]>('proactive_get_pending');
}

/**
 * Return proactive UI cards (richer shape than tasks — caller uses unknown[]).
 * Read-only.
 * @see proactive_vision.rs `pub fn proactive_get_cards() -> Vec<ProactiveCard>`
 */
export function proactiveGetCards(): Promise<unknown[]> {
  return invokeTyped<unknown[]>('proactive_get_cards');
}

/**
 * Return causal insight entries from the causal graph.
 * Read-only.
 * @see causal_graph.rs `pub fn causal_get_insights() -> Vec<CausalInsight>`
 */
export function causalGetInsights(): Promise<unknown[]> {
  return invokeTyped<unknown[]>('causal_get_insights');
}

/**
 * Predict likely consequences of a proposed action string.
 * @see consequence.rs `pub async fn consequence_predict(action: String) -> String`
 */
export function consequencePredict(action: string): Promise<string> {
  return invokeTyped<string, { action: string }>('consequence_predict', { action });
}

/**
 * Extract facts from a raw exchange string via the brain module.
 * @see brain.rs `pub async fn brain_extract_from_exchange(exchange: String) -> String`
 */
export function brainExtractFromExchange(exchange: string): Promise<string> {
  return invokeTyped<string, { exchange: string }>(
    'brain_extract_from_exchange',
    { exchange },
  );
}

/**
 * Returns true if dream mode (background LLM self-improvement loop) is active.
 * Read-only.
 * @see dream_mode.rs `pub fn dream_is_active() -> bool`
 */
export function dreamIsActive(): Promise<boolean> {
  return invokeTyped<boolean>('dream_is_active');
}

// ---------------------------------------------------------------------------
// Calendar — added in Plan 14-03 (WIRE2-02)
// @see src-tauri/src/tentacles/calendar_tentacle.rs `calendar_get_today`
// Returns today's calendar events. Safe when calendar tentacle is disabled —
// returns an empty array rather than an error.
// ---------------------------------------------------------------------------

/** A single calendar event as returned by calendar_tentacle.rs. */
export type CalendarEvent = {
  id: string;
  title: string;
  /** ISO-8601 datetime string */
  start: string;
  /** ISO-8601 datetime string */
  end: string;
  location?: string;
};

/**
 * Return today's calendar events.
 * Read-only. Errors caught silently by callers — calendar tentacle may be disabled.
 * @see calendar_tentacle.rs `pub fn calendar_get_today() -> Vec<CalendarEvent>`
 */
export function calendarGetToday(): Promise<CalendarEvent[]> {
  return invokeTyped<CalendarEvent[]>('calendar_get_today');
}

// ---------------------------------------------------------------------------
// Phase 36 — Intelligence Substrate (INTEL-01..06).
//
// Three Tauri commands surface to the frontend:
//   - reindex_symbol_graph (Plan 36-02 INTEL-01) — tree-sitter walk + persist
//   - reload_capability_registry (Plan 36-05 INTEL-04) — re-read JSON registry
//   - get_active_model_capabilities (Plan 36-05 INTEL-04) — current row
//
// Type shapes mirror the backend serde derives in src-tauri/src/intelligence/.
// All field names are snake_case at the IPC boundary (D-38, P-04 prevention).
//
// @see src-tauri/src/intelligence/symbol_graph.rs `pub struct ReindexStats`
// @see src-tauri/src/intelligence/capability_registry.rs `pub struct ModelCapabilities`
// @see .planning/phases/36-context-intelligence/36-CONTEXT.md
// ---------------------------------------------------------------------------

/**
 * Stats returned by reindex_symbol_graph after a tree-sitter pass over the
 * project root. Mirrors symbol_graph.rs::ReindexStats serde shape.
 */
export interface ReindexStats {
  files_walked: number;
  files_parsed: number;
  files_skipped: number;
  symbols_inserted: number;
  edges_inserted: number;
  elapsed_ms: number;
}

/**
 * Capability row returned by get_active_model_capabilities. Mirrors
 * capability_registry.rs::ModelCapabilities serde shape — sourced from the
 * canonical_models.json registry (Plan 36-05).
 */
export interface ModelCapabilities {
  context_length: number;
  tool_use: boolean;
  vision: boolean;
  audio: boolean;
  cost_per_million_in: number;
  cost_per_million_out: number;
  notes: string;
}

/**
 * Trigger a tree-sitter symbol-graph reindex pass over the given project root.
 * Runs synchronously on the chat command worker; large repos can block several
 * seconds — callers should provide a spinner.
 *
 * @see src-tauri/src/intelligence/symbol_graph.rs
 *      `pub async fn reindex_symbol_graph(project_root: String) -> Result<ReindexStats, String>`
 */
export function reindexSymbolGraph(projectRoot: string): Promise<ReindexStats> {
  return invokeTyped<ReindexStats, { project_root: string }>(
    'reindex_symbol_graph',
    { project_root: projectRoot },
  );
}

/**
 * Reload the capability registry from disk (canonical_models.json). Returns
 * the number of provider/model entries successfully loaded. Used by Settings
 * panes after the user edits the registry file or restores defaults.
 *
 * @see src-tauri/src/intelligence/capability_registry.rs
 *      `pub fn reload_capability_registry() -> Result<usize, String>`
 */
export function reloadCapabilityRegistry(): Promise<number> {
  return invokeTyped<number>('reload_capability_registry');
}

/**
 * Return the capability row for the currently-active provider/model pair, or
 * null when the active config doesn't match any registry entry. Surfaces
 * pricing + ctx-length + tool/vision/audio flags for the active route.
 *
 * @see src-tauri/src/intelligence/capability_registry.rs
 *      `pub fn get_active_model_capabilities() -> Option<ModelCapabilities>`
 */
export function getActiveModelCapabilities(): Promise<ModelCapabilities | null> {
  return invokeTyped<ModelCapabilities | null>('get_active_model_capabilities');
}
